name: dspy-env

dependencies:
  - python=3.11
  - pip
  - pip: 
    - backoff
    - joblib
    - jupyter
    - openai
    - pandas
    - spacy
    - regex
    - ujson
    - tqdm
    - datasets
    - requests
    - optuna
